Add Indonesian document
MlgmXyysd/Xiaomi-HyperOS-BootLoader-Bypass pull request #8
Opened 2023-11-25 22:48 UTC by bagasf2002

correct me if I'm wrong

2023-11-26 03:18 UTC, MlgmXyysd requested changes
Incorrect link on line 52 & 72

2023-11-26 15:29 UTC, bagasf2002 commented
Check sar

2023-11-26 15:30 UTC, bagasf2002 commented
> Incorrect link on line 52, 72 & 107

Check sar

2023-11-27 05:31 UTC, MlgmXyysd requested changes
Incorrect link on line 52, 72

2023-11-27 16:46 UTC, bagasf2002 commented
> Incorrect link on line 52, 72

Check sar

2023-11-29 19:13 UTC, MlgmXyysd requested changes
Same

2023-12-06 06:30 UTC, bagasf2002 commented
> Same

Cek sar

2024-01-05 04:37 UTC, MlgmXyysd requested changes
Incorrect link on line 52, 72

2024-01-05 04:37 UTC, MlgmXyysd commented on docs/README-id.md
Same

2024-02-19 08:06 UTC, MlgmXyysd commented
Close due to no responding

2024-02-19 08:06 UTC, closed without merging